--IDEE sp_DBMultiUser @DBName



USE [master]
GO
ALTER DATABASE [Kurs2014DB] SET  OFFLINE
GO
ALTER DATABASE [Kurs2014DB] SET  ONLINE
GO
use [master];
GO
ALTER DATABASE [Kurs2014DB] SET  MULTI_USER WITH NO_WAIT
GO




alter procedure sp_DBMultiUser @DBname nvarchar(50)
as
exec 'ALTER DATABASE @DBname SET  OFFLINE'
GO
ALTER DATABASE @DBname SET  ONLINE
GO
ALTER DATABASE @DBname SET  MULTI_USER WITH NO_WAIT

